import streamlit as st
import google.generativeai as genai
import os
from st_paywall import add_indentification
from datetime import datetime

# --- 1. COMPLIANCE & UI CONFIG ---
st.set_page_config(page_title="Zyntra AI", page_icon="🧘", layout="wide")

# CSS for Legal Compliance (Sticky Footer)
st.markdown("""
    <style>
    .reportview-container .main .footer { position: fixed; bottom: 0; }
    .ai-label { color: #888; font-size: 0.8em; margin-top: -10px; margin-bottom: 10px; }
    </style>
    """, unsafe_allow_html=True)

# --- 2. THE SUBSCRIPTION GATEWAY ---
# This handles the 2026 'Right to Withdraw' and secure Stripe payment
add_indentification(
    reporting_url="https://zyntra.ai", # Change to your actual URL
    publishable_key=st.secrets["STRIPE_PUBLISHABLE_KEY"]
)

# Determine Tier (Logic: If subscribed = Pro/Max, else Free)
user_tier = "Free"
if st.session_state.get("user_subscribed"):
    # In Stripe, 'Max' is your monthly product, 'Pro' is your 3-month product
    user_tier = st.session_state.get("subscription_tier", "Pro") 

# --- 3. AI ENGINE SETUP ---
genai.configure(api_key=st.secrets["GOOGLE_API_KEY"])

# System Instructions based on 2026 Safety Guidelines
base_prompt = (
    "You are Zyntra, a high-fidelity AI. "
    "MANDATORY: You must prioritize electrical safety for ESP32-CAM projects. "
    "Always remind users to disconnect power before wiring."
)

model = genai.GenerativeModel(
    model_name="gemini-1.5-flash" if user_tier == "Free" else "gemini-1.5-pro",
    system_instruction=base_prompt
)

# --- 4. THE FRONTEND ---
st.title(f"🧘 Zyntra {user_tier}")

# Mandatory DPDP Act Consent (New for 2026)
if "legal_consent" not in st.session_state:
    st.session_state.legal_consent = False

if not st.session_state.legal_consent:
    with st.expander("Required: Data & Safety Consent", expanded=True):
        st.write("To comply with DPDP 2026, we need your consent:")
        c1 = st.checkbox("I agree to the Privacy Policy and processing of my prompts.")
        c2 = st.checkbox("I understand Zyntra is an AI and I am responsible for my hardware safety.")
        if st.button("Accept & Enter Zyntra"):
            if c1 and c2:
                st.session_state.legal_consent = True
                st.rerun()
            else:
                st.error("Please accept all terms to continue.")
    st.stop()

# --- 5. SUBSCRIPTION DASHBOARD ---
if user_tier == "Free":
    with st.container(border=True):
        st.markdown("### 🚀 Upgrade Your Intelligence")
        col1, col2 = st.columns(2)
        with col1:
            st.write("**Zyntra Pro**")
            st.write("⚡ Full Hardware Code | $99 per 3 Months")
            st.link_button("Get Pro", st.secrets["STRIPE_PRO_LINK"])
        with col2:
            st.write("**Zyntra Max**")
            st.write("💎 Elite Logic | 1 Month FREE, then $199/mo")
            st.link_button("Try Max Free", st.secrets["STRIPE_MAX_LINK"])

# --- 6. CHAT ENGINE ---
if "messages" not in st.session_state:
    st.session_state.messages = []

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if msg["role"] == "assistant":
            st.markdown('<p class="ai-label">✨ Synthetically Generated by Zyntra</p>', unsafe_allow_html=True)

if prompt := st.chat_input("Ask Zyntra..."):
    # Rate Limiting for Free Tier
    if user_tier == "Free" and len(st.session_state.messages) >= 10:
        st.error("Free daily limit reached. Please upgrade to Pro for unlimited hardware support.")
    else:
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        with st.chat_message("assistant"):
            response = model.generate_content(prompt)
            st.markdown(response.text)
            st.markdown('<p class="ai-label">✨ Synthetically Generated by Zyntra</p>', unsafe_allow_html=True)
            st.session_state.messages.append({"role": "assistant", "content": response.text})

# --- 7. LEGAL FOOTER ---
st.divider()
st.caption(f"""
    © {datetime.now().year} Zyntra Labs. 
    **Liability Disclaimer:** AI suggestions can be wrong. Use a multimeter before testing ESP32-CAM circuits. 
    **Data Rights:** You can request data deletion via your profile settings. 
    **SGI Notice:** This platform uses Synthetically Generated Information under IT Rules 2026.
""")